name: ci

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

env:
  NODE_VERSION: 24

jobs:
  check:
    runs-on: [ self-hosted, Linux, X64, stavi-dev ]
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: lint
        run: pnpm lint